cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED _BOQ_COMPILER_WAS_SETUP)
    set(_BOQ_COMPILER_WAS_SETUP ON)
    if(MSVC)
        include(${CMAKE_CURRENT_LIST_DIR}/MsvcSetup.cmake)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES ".*[cC]lang")
        include(${CMAKE_CURRENT_LIST_DIR}/ClangSetup.cmake)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        include(${CMAKE_CURRENT_LIST_DIR}/GccSetup.cmake)
    else()
        message(FATAL_ERROR "Unsupported compiler: ${CMAKE_CXX_COMPILER_ID}")
    endif()
endif()